version: 2

updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      time: '12:00'
      timezone: EST
    open-pull-requests-limit: 2
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: '12:00'
      timezone: EST
    open-pull-requests-limit: 99
    allow:
      - dependency-type: direct
