container:
  image: node:10

build_task:
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true'
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  relay_script: yarn run relay
  build_script: yarn run build

deploy_docker_builder:
  only_if: $CIRRUS_BRANCH == "master"
  depends_on: build
  environment:
    DOCKER_USER_NAME: ENCRYPTED[5eb941ed91706fab3eb53bfd01dc3b88caee18e11f9df18b4663875f83e9e390eeb0db087278035b61bf5b24e8f96328]
    DOCKER_PASSWORD: ENCRYPTED[5e9b3eb1391a7a0cf259c41920ce60d034660cc49f0b85b2738eb53d9a537b90d0d2173d6321096facd11f5e5a9e31c3]
  build_script:
    - docker --version
    - ./.ci/build_docker.sh
  push_script: ./.ci/push_docker.sh
