container:
  image: node:14
  memory: 6G

task:
  use_compute_credits: $CIRRUS_BRANCH == 'master'
  install_script: yarn
  bootstrap_script: yarn bootstrap
  matrix:
    - name: Build
      build_script: yarn build
    - name: Tests
      test_script: yarn test
    - name: Prettier
      prettier_check_script: yarn prettier-check
    - name: Type Check
      typecheck_script: yarn typecheck

deploy_docker_builder:
  only_if: $CIRRUS_BRANCH == "master"
  depends_on:
    - Build
    - Prettier
    - Type Check
  environment:
    DOCKER_USER_NAME: ENCRYPTED[5eb941ed91706fab3eb53bfd01dc3b88caee18e11f9df18b4663875f83e9e390eeb0db087278035b61bf5b24e8f96328]
    DOCKER_PASSWORD: ENCRYPTED[5e9b3eb1391a7a0cf259c41920ce60d034660cc49f0b85b2738eb53d9a537b90d0d2173d6321096facd11f5e5a9e31c3]
  build_script:
    - docker --version
    - ./.ci/build_docker.sh
  push_script: ./.ci/push_docker.sh
