version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "RDIL"
      - "fkorotkov"
    target_branch: "master"
    allowed_updates:
      - match:
        update_type: "all"
    version_requirement_updates: "increase_versions"
    
